name: horizontal_calendar_view_widget
description: Easy to use, highly customizable horizontal calendar. Single or up to x days selection, with Internationalization support.
version: 2.1.2
homepage: https://github.com/dev-vivek-ri/horizontal_calendar

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  scrollable_positioned_list: ^0.3.2

dev_dependencies:
  lint: ^1.10.0
  flutter_test:
    sdk: flutter