name: Run lint on pull requests
on:
  pull_request:
  push:

jobs:
  lint:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
